src/kinds.rs, src/macros.rs, src/parser.rs, src/tokenizer.rs, src/types.rs, test_data/parser/merge/1.expect
according to src/libexpr/lexer.l, nix calls `//` the UPDATE token
see https://github.com/nixos/nix/blob/f435634a29551754d5f7303b0a60cd8fe2df2079/src/libexpr/lexer.l#L122
=> rename TOKEN_MERGE to TOKEN_UPDATE

src/kinds.rs, src/parser.rs, src/types.rs, test_data/general/docs.expect, test_data/general/interpolation.expect, test_data/general/isset.expect, test_data/parser/index_set/1.expect, test_data/parser/index_set/3.expect, test_data/parser/interpolation/1.expect, test_data/parser/invalid_syntax/1.expect, test_data/parser/isset/2.expect
index_set is confusing, because it sounds like another kind of
attr_set, where attributes are numeric.
select is not super clear either, but I personally find it less
confusing and it is what the original parser uses
=> rename index_set to select

src/types.rs
**Rationale**: This convenience function was missing for me when implementing some analysis on function scopes. This should make it easier to get all identifiers that are defined by a function call.
=> Add pattern.at function to get ident@{} pattern

src/types.rs
This allows `ParsedType`, which only encapsulates items with trait `TypedNode` to be used as a `TypedNode`.
=> Implement TypedNode for ParsedType

src/parser.rs, test_data/parser/inherit/1.expect, test_data/parser/inherit/1.nix
Nix allows code like `inherit ${"foo"}` to inherit the "foo" attribute.
This was previously parsed as invalid code while nix allows using that.
This is a follow-up to a conversation I had with @jD91mZM2 a while ago on IRC. I hope I got the implementation right because I mostly guessed from the notes I took back then.
=> Support parsing dynamic inherit identifiers

src/types.rs
While consuming the output of this library it is sometimes very helpful
to have a printable represntation of `ParsedType`.
=> types: provide a Debug instance for ParsedType

src/parser.rs, test_data/parser/inherit/2.expect, test_data/parser/inherit/2.nix
First of all, big thanks to @fufexan who helped me to reliably reproduce
this.
Originally discovered in `rnix-lsp`[1], but I confirmed that
`nixpkgs-fmt` is also affected.
Basically, when having an expression such as
let
inherit
the parser would wait for a `TOKEN_SEMICOLON` indefinitely. The actual
problem however is that `self.parse_val()` always detects the SAME
syntax-error, i.e. "unexpected EOF". This will be written indefinetely
into `self.errors`. However, `errors` is of type `Vec<ParseError>` and a
vector in Rust grows in an amortized fashion[2] which means that if an
entry is pushed and the vector exceeds the currently allocated size, it
will be ~doubled (though the exact growth-factor isn't constant).
This essentially means that the buffer is growing exponentially pretty fast
and …
=> Fix memory leak while parsing improperly terminated `inherit`-expressions

src/lib.rs, src/types.rs
Since rowan produces syntax trees even if there are errors present in
the source, every function that operates on the tree has to assume that
syntax nodes are partially constructed. As a result, every function on
the tree should return an optional value.
This is already the case with most functions, `BinOp::operator` has been
updated to behave the same way.
This PR closes  #30.
=> make BinOp::operator return an optional value

README.md, examples/from-stdin.rs
When debugging #46 I wanted to narrow down the failing snippet. Using a file was too unwiedly.
You can run this snippet with `echo "0.5" | cargo run --quiet --example from-stdin`
=> example for stdin parsing

src/parser.rs
a couple of enum variants were incorrectly named in the doc comments of
ParseError.
=> minor fix to doc of ParseError

src/tokenizer.rs
* Floats without leading zeroes (e.g. `.5`) are valid nix code
n/a
Fixes #46
cc @aaronjanse @efx
=> Floats without trailing zeros (e.g. `.5`) are valid Nix code

src/types.rs, src/value.rs
Fixes #66.
- `rnix::types::StrPart::Ast(SyntaxNode)` -> `rnix::types::StrPart::Ast(StrInterpol)`
- Adds `rnix::types::TypedNode::ParsedType::StrInterpol`
=> Add type for STRING_INTERPOL

src/types.rs
`UnaryOp::operator` should not panic if the AST is incomplete, and should return `None` instead. This is also now uniform with `BinaryOp::operator`.
Changes the return type of `UnaryOp::operator`.
=> make UnaryOp::operator return Option<UnaryOpKind>

src/lib.rs, src/tokenizer.rs
The `Tokenizer` doc mentions using the `tokenize` convenience function, but this isn't exported from the module.
This is slightly nicer than constructing and collecting the Tokenizer manually, because the type is explicit. i.e., compare
```rust
let tokens = Tokenizer::new(input).collect::<Vec<(SyntaxKind, SmolStr)>>();
```
vs
```rust
let tokens = tokenize(input);
```
=> Export tokenize function from tokenizer module

flake.nix
Fixes out of date version in the flake package and keeps it synchronized with the version in Cargo.toml
=> keep flake package version in sync with Cargo.toml

Cargo.toml, flake.lock
* Update flake inputs using `nix flake update --commit-lock-file`. Primarily, this bumps the rustc/cargo version to 1.61.0.
* Move to Rust 2021 edition (verified no changes are necessary with `cargo fix --edition`, and all tests are green!)
This is a smaller alternative to #58 while issues there are resolved.
=> Move to Rust 2021 (smaller)

Cargo.lock, Cargo.toml, examples/list-fns.rs, src/parser.rs, src/tokenizer.rs
remove smol-str, broken out of #36 (although I've done it from scratch in this PR). => to reduce the scope of #36.
I haven't checked if/where `SmolStr` might've leaked into public API, but I needed to modify a single example and some tests, to this is probably backward-incompatible.
=> refactor: get rid of smol-str dependency

Cargo.lock, Cargo.toml, examples/list-fns.rs, src/lib.rs, src/types.rs
upgrade `rowan` to v0.15, broken out of https://github.com/nix-community/rnix-parser/pull/36 (although I've done it from scratch in this PR). => to reduce the scope of https://github.com/nix-community/rnix-parser/pull/36.
* replaces `TokenWrapper::as_str :: . -> &str` with `TokenWrapper::to_inner_string :: . -> String`. I didn't know how to access the inner green node + children without allocations or dangling references... I added a note about that to the docstring
* `Value::to_value` now uses a different way to retrieve the token kind, which should usually be equivalent, but I don't know if this breaks any edge case
=> chore+refactor: upgrade rowan to v0.15

src/tokenizer.rs
Previously, if the tokenizer encountered the sequence of characters `''\$`, `next_string` would consume the first 3 and then loop back around and see the `$` next, which it treated as the start of an interpolation.
With this change, it will instead always immediately consume the next character after `''\` before looping back. This is correct, because [`''\x` is a valid escape sequence for any `x`](https://github.com/NixOS/nix/blob/59764eb842d0da4f6fcf4ce4b85bf02ac1ae26fc/src/libexpr/lexer.l#L218).
Fixes #100
=> Fix multiline dollar escape

src/ast/nodes.rs, src/ast/operators.rs, src/kinds.rs, src/macros.rs, src/parser.rs, src/tokenizer.rs, test_data/general/isset.expect, test_data/general/or-as-ident.expect, test_data/general/or-as-ident.nix, test_data/parser/ifs/1.expect, test_data/parser/ifs/2.expect, test_data/parser/ifs/3.expect, test_data/parser/isset/1.expect, test_data/parser/isset/2.expect
See details in https://github.com/nix-community/rnix-parser/pull/106#issuecomment-1193152913
- Parse "or" as a keyword by default, used as selection with default.
Eg. `a.b or c`
- When expecting an attribute, accept "or" and make it an identifier.
Eg. `let or.or = 1; in ...`
- When parsed a primary expression, with not "." following, and the next
token is "or", it is consumed as an identifier and an application node
is immediately constructed, ignoring the the associativity of ancestor
applications.
Eg. `a b or c` is grouped as `((a (b or)) c)`
- Otherwise, "or" is disallowed.
Eg. `or 1` will fail.
- TOKEN_OR -> TOKEN_OR_OR
- TOKEN_AND -> TOKEN_AND_AND
=> Mimic Nix's behavior of contextual keyword "or"

Cargo.lock, fuzz/Cargo.lock, fuzz/Cargo.toml, fuzz/rust-toolchain.toml, src/kinds.rs, src/parser.rs, src/tokenizer.rs, test_data/general/dynamic-attrs.expect, test_data/parser/index_set/3.expect, test_data/parser/inherit/1.expect, test_data/parser/isset/multiple.expect, test_data/parser/paths/4.expect, test_data/parser/set/4.expect
Fixes error introduced in #102 because we weren't checking for `None`. Refactors the lexer to use the context only instead of duplicating it in struct fields. Make  tests cleaner and shorter by removing `tokens` macro.
=> Lexer refactor

src/ast.rs
Re-export `LiteralKind` from `ast`. I don't think it is possible to use currently.
=> Export LiteralKind from ast

src/ast/nodes.rs
Removes Inherit and InheritFrom variants from the typed Expr enum
Removed `ast::Expr::Inherit` and `ast::Expr::InheritFrom`
Fixes #125 
There might be some reason that I'm missing for why these should be `Expr`s.
=> Remove Expr Inherit and InheritFrom variants

src/ast/nodes.rs
Add missing impl for typed `Dynamic` node, primarily to get access to the inner expression.
I opted to write `TOKEN_INTERPOL_START` and `TOKEN_INTERPOL_END` directly instead of adding cases to the `T` macro, because the latter overlaps with `TOKEN_CURLY_B_CLOSE`.
=> Add getters for typed Dynamic parts

src/parser.rs, test_data/parser/success/pattern_bind_left.expect, test_data/parser/success/pattern_default.expect, test_data/parser/success/pattern_default_attrset.expect, test_data/parser/success/pattern_default_ellipsis.expect, test_data/parser/success/pattern_trailing_comma.expect
Fixes getting the ident from a PatEntry here:
https://github.com/nix-community/rnix-parser/blob/f8056c4811b6f5196af64db14b89651e892ad98a/src/ast/nodes.rs#L356-L357
=> Wrap pat entry ident in NODE_IDENT

.gitattributes, benches/all-packages.nix
It seems there's some problems / recent breakage when trying to clone repositories with git-lfs enabled from a nix build.
In https://code.tvl.fyi/tree/tvix/eval, we're referring to rnix-parser from Cargo.lock, by git rev.
This seems to fail with more recent versions (>2.3) of Nix, due to some git-lfs issues:
```
mg build //tvix/eval
[mg] building target //tvix/eval
Downloading benches/all-packages.nix (803 KB)
Error downloading object: benches/all-packages.nix (935f239): Smudge error: Error downloading benches/all-packages.nix (935f239a576caa554e546072772039f6efcbde2f2e6568733b8857fe476c5604): batch request: missing protocol: ""
Errors logged to '/home/flokli/.cache/nix/gitv3/1qzfb517dymd9fbs5nznalj8803yx2mzy4wzjxfr1wqfc3nj00q2/lfs/logs/20220916T124822.679316329.log'.
Use `git lfs logs …
```
=> un-git-lfs benches/all-packages.nix

src/ast/nodes.rs, src/tests.rs
`idents` returns all the identifiers in the `InheritFrom`, but the correct thing to return is all the `Attr`.
https://github.com/NixOS/nix/blob/master/src/libexpr/parser.y#L542
=> change Inherit::idents to Inherit::attrs

examples/from-stdin.rs
It's not that useful to exact print what is passed from stdin.
=> pretty print ast for from-stdin example

Cargo.toml
I realized my previous PR needed a semver bump, since it added variants to a public enum which is a breaking change (users' match statements could become non-exhaustive and error).
=> Bumped library version
